# Generated by Django 6.1.1 on 2026-09-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('instrument_type', models.CharField(choices=[('WEIGHING_SCALE', 'Weighing Scale'), ('ELECTRONIC_BALANCE', 'Electronic Balance'), ('PLATFORM_SCALE', 'Platform Scale'), ('FUEL_DISPENSER', 'Fuel Dispenser'), ('WATER_METER', 'Water Meter'), ('MEASURING_INSTRUMENT', 'Measuring Instrument'), ('OTHER', 'Other')], max_length=40)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('capacity_range', models.CharField(blank=True, max_length=255)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
